language: python
python:
  # - "2.6"
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  - "3.4"
  - "3.5"

cache: pip

install: 
  - pip install -r requirements.txt
# command to run tests
script: 
  - python selfDrivingCar_test.py

notifications:
  email:
    recipients:
      - mingerz.k@gmail.com 
    on_success: change
    on_failure: always